---
version: '1.0'
kind: pipeline
metadata:
  name: ForgeCloud/saas/customer-environment
  isPublic: false
  labels:
    tags: []
  deprecate:
    applicationPort: '8080'
    repoPipeline: true
  project: ForgeCloud/saassdfsfddf
spec:
  triggers:
  - name: deploy-services
    type: git
    repo: kim-codefresh/pipelines
    events:
    - push
    branchRegex: "/.*/gi"
    modifiedFilesGlob: "{\
    ,deploy/autoaccess/**\
    ,deploy/bin/**\
    ,deploy/codefresh/*.ce.steps.yml\
    ,deploy/codefresh/auto-environment.steps.yml\
    ,deploy/codefresh/customer-environment.steps.yml\
    ,deploy/docker/fbc-tools/**\
    ,deploy/docker/util/**\
    ,deploy/kustomize/**\
    ,deploy/terraform/**\
    ,go.{mod,sum}\
    ,go/common/**\
    ,tools/forge/**\
    ,go/services/customer/**\
    ,go/services/orchestration/orch-common/**\
    ,go/services/org-bootstrapper/**\
    ,go/utilities/engine-checker/**\
    ,services/cert-manager/**\
    ,services/edgedelta/**\
    ,services/elasticsearch-exporter/**\
    ,services/forgecloud/**\
    ,services/gatekeeper/**\
    ,services/haproxy/**\
    ,services/intezer/**\
    ,services/kube-state-metrics/**\
    ,services/org-filter/**\
    ,services/org-log-spewer/**\
    ,services/prometheus*/**\
    ,services/thanos/**\
    }"
    provider: github
    context: github-11
  contexts:
  - kim-codefresh
  variables:
  - key: CF_SKIP_MAIN_CLONE
    value: 'true'
  - key: FLOATING_IMAGE_TAG
    value: "${{CF_BRANCH_TAG_NORMALIZED}}"
  - key: STATIC_IMAGE_TAG
    value: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_REVISION}}"
    # This pipeline is optimized to only build Docker images deployed by org-engine if their source has changed;
    # use the following variables to force a given stage. Default is not to force a stage unless a change has been detected.
    # - key: FORCE_BUILD_<STAGE_NAME> (eg FORCE_BUILD_ORG_ENGINE)
    #   value: "true"
  specTemplate:
    location: git
    repo: kim-codefresh/pipelines
    path: customer-environment.steps.yml
    context: github-1
  steps: {}
  stages: []
  concurrency: 6
  branchConcurrency: 1
