version: '1.0'
steps:
  step_1:
    image: alpine
    commands:
      - export sdd=true
      - printenv | grep sdd
      - cf_export mjk=
  step_2:
    image: alpineee
    # variables:
    #  - key: dd
    #    value: "my-value"
    commands:
     - printenv | grep sdd
     - printenv | grep mjk
     - cf_export sdd="new_var"
     # - printenv | grep dd
  step_3:
    image: alpine
    commands:
      - printenv | grep sdd
  # simple_Step:
  #   title: Simple step
  #   type: francisco-codefresh/simple-step
  #   arguments:
  #     ARG_1: ${{PIPELINE_VAR}}
  #     ARG_2: ${{CF_BUILD_ID}}
  #     ARG_3: 'value_3'
id: 65954c344112deaa0f8271fb
spec:
triggers:
- name: new-repo
  type: git
  repo: kim-codefresh/new-repo
  events:
    - push.heads
  pullRequestAllowForkEvents: false
  commentRegex: /.*/gi
  branchRegex: /.*/gi
  branchRegexInput: regex
  gerritCIStatusLabels: []
  provider: github
  disabled: false
  options:
    noCache: false
    noCfCache: false
    resetVolume: false
  verified: true
  context: github
  contexts: []
  variables:
    - key: tr
      value: ''
  status: verified
  lastExecutionDate: '2024-01-16T09:09:28.805Z'
  id: 6582832cc16cea45e53fe3fb
  endpoint: 'http://kim-platform.ngrok.io//mW5k1qwcZ1'
  secret: hZFNooRBNGgh7dnJ
stages: []
variables:
- key: mjk
  value: 'true'
  encrypted: false
contexts: []
terminationPolicy: []
externalResources: []
options:
keepPVCsForPendingApproval: true
steps:
step_1:
  image: alpine
  commands:
    - export sdd=true
    - printenv | grep sdd
    - cf_export mjk=
step_2:
  image: alpineee
  commands:
    - printenv | grep sdd
    - printenv | grep mjk
    - cf_export sdd="new_var"
step_3:
  image: alpine
  commands:
    - printenv | grep sdd
